/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface AuditInterface extends Interface {
    getFunction(nameOrSignature: "getEntriesForRef" | "getEntry" | "logAudit" | "totalEntries"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuditLogged"): EventFragment;

    encodeFunctionData(functionFragment: 'getEntriesForRef', values: [string]): string;
encodeFunctionData(functionFragment: 'getEntry', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'logAudit', values: [string, string, string]): string;
encodeFunctionData(functionFragment: 'totalEntries', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'getEntriesForRef', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEntry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'logAudit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalEntries', data: BytesLike): Result;
  }

  
    export namespace AuditLoggedEvent {
      export type InputTuple = [index: BigNumberish, eventType: string, referenceId: string, actor: string, timestamp: BigNumberish];
      export type OutputTuple = [index: bigint, eventType: string, referenceId: string, actor: string, timestamp: bigint];
      export interface OutputObject {index: bigint, eventType: string, referenceId: string, actor: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Audit extends BaseContract {
    
    connect(runner?: ContractRunner | null): Audit;
    waitForDeployment(): Promise<this>;

    interface: AuditInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getEntriesForRef: TypedContractMethod<
      [referenceId: string, ],
      [bigint[]],
      'view'
    >
    

    
    getEntry: TypedContractMethod<
      [index: BigNumberish, ],
      [[string, string, string, bigint] & {eventType: string, referenceId: string, actor: string, timestamp: bigint }],
      'view'
    >
    

    
    logAudit: TypedContractMethod<
      [eventType: string, referenceId: string, actor: string, ],
      [void],
      'nonpayable'
    >
    

    
    totalEntries: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getEntriesForRef'): TypedContractMethod<
      [referenceId: string, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getEntry'): TypedContractMethod<
      [index: BigNumberish, ],
      [[string, string, string, bigint] & {eventType: string, referenceId: string, actor: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'logAudit'): TypedContractMethod<
      [eventType: string, referenceId: string, actor: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalEntries'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'AuditLogged'): TypedContractEvent<AuditLoggedEvent.InputTuple, AuditLoggedEvent.OutputTuple, AuditLoggedEvent.OutputObject>;

    filters: {
      
      'AuditLogged(uint256,string,string,string,uint256)': TypedContractEvent<AuditLoggedEvent.InputTuple, AuditLoggedEvent.OutputTuple, AuditLoggedEvent.OutputObject>;
      AuditLogged: TypedContractEvent<AuditLoggedEvent.InputTuple, AuditLoggedEvent.OutputTuple, AuditLoggedEvent.OutputObject>;
    
    };
  }