/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface IntegrityInterface extends Interface {
    getFunction(nameOrSignature: "commitHash" | "getHash" | "getLatestVersion" | "isCommitted" | "verifyHash"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "HashCommitted"): EventFragment;

    encodeFunctionData(functionFragment: 'commitHash', values: [string, BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getHash', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLatestVersion', values: [string]): string;
encodeFunctionData(functionFragment: 'isCommitted', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifyHash', values: [string, BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'commitHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLatestVersion', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isCommitted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyHash', data: BytesLike): Result;
  }

  
    export namespace HashCommittedEvent {
      export type InputTuple = [fileId: string, version: BigNumberish, contentHash: string, timestamp: BigNumberish];
      export type OutputTuple = [fileId: string, version: bigint, contentHash: string, timestamp: bigint];
      export interface OutputObject {fileId: string, version: bigint, contentHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Integrity extends BaseContract {
    
    connect(runner?: ContractRunner | null): Integrity;
    waitForDeployment(): Promise<this>;

    interface: IntegrityInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    commitHash: TypedContractMethod<
      [fileId: string, version: BigNumberish, contentHash: string, ],
      [void],
      'nonpayable'
    >
    

    
    getHash: TypedContractMethod<
      [fileId: string, version: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getLatestVersion: TypedContractMethod<
      [fileId: string, ],
      [bigint],
      'view'
    >
    

    
    isCommitted: TypedContractMethod<
      [fileId: string, version: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    verifyHash: TypedContractMethod<
      [fileId: string, version: BigNumberish, contentHash: string, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'commitHash'): TypedContractMethod<
      [fileId: string, version: BigNumberish, contentHash: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getHash'): TypedContractMethod<
      [fileId: string, version: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getLatestVersion'): TypedContractMethod<
      [fileId: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isCommitted'): TypedContractMethod<
      [fileId: string, version: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'verifyHash'): TypedContractMethod<
      [fileId: string, version: BigNumberish, contentHash: string, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'HashCommitted'): TypedContractEvent<HashCommittedEvent.InputTuple, HashCommittedEvent.OutputTuple, HashCommittedEvent.OutputObject>;

    filters: {
      
      'HashCommitted(string,uint256,string,uint256)': TypedContractEvent<HashCommittedEvent.InputTuple, HashCommittedEvent.OutputTuple, HashCommittedEvent.OutputObject>;
      HashCommitted: TypedContractEvent<HashCommittedEvent.InputTuple, HashCommittedEvent.OutputTuple, HashCommittedEvent.OutputObject>;
    
    };
  }