/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface OwnershipInterface extends Interface {
    getFunction(nameOrSignature: "getOwner" | "isRegistered" | "registerOwnership" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipRegistered" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'getOwner', values: [string]): string;
encodeFunctionData(functionFragment: 'isRegistered', values: [string]): string;
encodeFunctionData(functionFragment: 'registerOwnership', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [string, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRegistered', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace OwnershipRegisteredEvent {
      export type InputTuple = [fileId: string, owner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [fileId: string, owner: string, timestamp: bigint];
      export interface OutputObject {fileId: string, owner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [fileId: string, previousOwner: AddressLike, newOwner: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [fileId: string, previousOwner: string, newOwner: string, timestamp: bigint];
      export interface OutputObject {fileId: string, previousOwner: string, newOwner: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Ownership extends BaseContract {
    
    connect(runner?: ContractRunner | null): Ownership;
    waitForDeployment(): Promise<this>;

    interface: OwnershipInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getOwner: TypedContractMethod<
      [fileId: string, ],
      [string],
      'view'
    >
    

    
    isRegistered: TypedContractMethod<
      [fileId: string, ],
      [boolean],
      'view'
    >
    

    
    registerOwnership: TypedContractMethod<
      [fileId: string, owner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [fileId: string, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getOwner'): TypedContractMethod<
      [fileId: string, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isRegistered'): TypedContractMethod<
      [fileId: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerOwnership'): TypedContractMethod<
      [fileId: string, owner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [fileId: string, newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipRegistered'): TypedContractEvent<OwnershipRegisteredEvent.InputTuple, OwnershipRegisteredEvent.OutputTuple, OwnershipRegisteredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OwnershipRegistered(string,address,uint256)': TypedContractEvent<OwnershipRegisteredEvent.InputTuple, OwnershipRegisteredEvent.OutputTuple, OwnershipRegisteredEvent.OutputObject>;
      OwnershipRegistered: TypedContractEvent<OwnershipRegisteredEvent.InputTuple, OwnershipRegisteredEvent.OutputTuple, OwnershipRegisteredEvent.OutputObject>;
    

      'OwnershipTransferred(string,address,address,uint256)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }