/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PermissionInterface extends Interface {
    getFunction(nameOrSignature: "checkPermission" | "getPermission" | "grantPermission" | "revokePermission"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "PermissionGranted" | "PermissionRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'checkPermission', values: [string, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'getPermission', values: [string, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'grantPermission', values: [string, AddressLike, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokePermission', values: [string, AddressLike, string]): string;

    decodeFunctionResult(functionFragment: 'checkPermission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPermission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantPermission', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokePermission', data: BytesLike): Result;
  }

  
    export namespace PermissionGrantedEvent {
      export type InputTuple = [fileId: string, grantee: AddressLike, action: string, expiry: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [fileId: string, grantee: string, action: string, expiry: bigint, timestamp: bigint];
      export interface OutputObject {fileId: string, grantee: string, action: string, expiry: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PermissionRevokedEvent {
      export type InputTuple = [fileId: string, grantee: AddressLike, action: string, timestamp: BigNumberish];
      export type OutputTuple = [fileId: string, grantee: string, action: string, timestamp: bigint];
      export interface OutputObject {fileId: string, grantee: string, action: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Permission extends BaseContract {
    
    connect(runner?: ContractRunner | null): Permission;
    waitForDeployment(): Promise<this>;

    interface: PermissionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    checkPermission: TypedContractMethod<
      [fileId: string, grantee: AddressLike, action: string, ],
      [boolean],
      'view'
    >
    

    
    getPermission: TypedContractMethod<
      [fileId: string, grantee: AddressLike, action: string, ],
      [[boolean, bigint] & {exists: boolean, expiry: bigint }],
      'view'
    >
    

    
    grantPermission: TypedContractMethod<
      [fileId: string, grantee: AddressLike, action: string, expiry: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokePermission: TypedContractMethod<
      [fileId: string, grantee: AddressLike, action: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'checkPermission'): TypedContractMethod<
      [fileId: string, grantee: AddressLike, action: string, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'getPermission'): TypedContractMethod<
      [fileId: string, grantee: AddressLike, action: string, ],
      [[boolean, bigint] & {exists: boolean, expiry: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'grantPermission'): TypedContractMethod<
      [fileId: string, grantee: AddressLike, action: string, expiry: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokePermission'): TypedContractMethod<
      [fileId: string, grantee: AddressLike, action: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'PermissionGranted'): TypedContractEvent<PermissionGrantedEvent.InputTuple, PermissionGrantedEvent.OutputTuple, PermissionGrantedEvent.OutputObject>;
getEvent(key: 'PermissionRevoked'): TypedContractEvent<PermissionRevokedEvent.InputTuple, PermissionRevokedEvent.OutputTuple, PermissionRevokedEvent.OutputObject>;

    filters: {
      
      'PermissionGranted(string,address,string,uint256,uint256)': TypedContractEvent<PermissionGrantedEvent.InputTuple, PermissionGrantedEvent.OutputTuple, PermissionGrantedEvent.OutputObject>;
      PermissionGranted: TypedContractEvent<PermissionGrantedEvent.InputTuple, PermissionGrantedEvent.OutputTuple, PermissionGrantedEvent.OutputObject>;
    

      'PermissionRevoked(string,address,string,uint256)': TypedContractEvent<PermissionRevokedEvent.InputTuple, PermissionRevokedEvent.OutputTuple, PermissionRevokedEvent.OutputObject>;
      PermissionRevoked: TypedContractEvent<PermissionRevokedEvent.InputTuple, PermissionRevokedEvent.OutputTuple, PermissionRevokedEvent.OutputObject>;
    
    };
  }