"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 21:22:28.962286
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_outbox_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_outbox_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_outbox_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('employee', 'manager', 'admin', 'auditor', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_address')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('protection_mode', sa.Enum('none', 'append_only', 'read_only', name='protectionmode', native_enum=False, length=20), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('approved_version', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_owner_id'), ['owner_id'], unique=False)

    op.create_table('approvals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('request_comment', sa.String(length=500), nullable=False),
    sa.Column('decision_comment', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_requested_by'), ['requested_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('file_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('rolled_back_from', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'version_number', name='uq_file_version')
    )
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_versions_file_id'), ['file_id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Enum('read', 'write', 'manage', name='permissionlevel', native_enum=False, length=20), nullable=False),
    sa.Column('granted_by', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permissions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_user_id'))
        batch_op.drop_index(batch_op.f('ix_permissions_file_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_versions_file_id'))

    op.drop_table('file_versions')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_requested_by'))
        batch_op.drop_index(batch_op.f('ix_approvals_file_id'))

    op.drop_table('approvals')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_owner_id'))

    op.drop_table('files')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('audit_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_outbox_status'))
        batch_op.drop_index(batch_op.f('ix_audit_outbox_reference_id'))
        batch_op.drop_index(batch_op.f('ix_audit_outbox_event_type'))

    op.drop_table('audit_outbox')
    # ### end Alembic commands ###
