"""create audit outbox table

Revision ID: 4d530504bb65
Revises: 
Create Date: 2026-09-29 02:31:17.173856

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d530504bb65'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_outbox_event_type'), 'audit_outbox', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_outbox_reference_id'), 'audit_outbox', ['reference_id'], unique=False)
    op.create_index(op.f('ix_audit_outbox_status'), 'audit_outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_outbox_status'), table_name='audit_outbox')
    op.drop_index(op.f('ix_audit_outbox_reference_id'), table_name='audit_outbox')
    op.drop_index(op.f('ix_audit_outbox_event_type'), table_name='audit_outbox')
    op.drop_table('audit_outbox')
    # ### end Alembic commands ###
